import { useState, useCallback } from 'react';
import Header from './components/Header';
import Hero from './components/Hero';
import CoverForm from './components/CoverForm';
import OutputPanel from './components/OutputPanel';
import { callGeminiAPI, buildTemplateLetter, markdownToHtml } from './utils/gemini';
import styles from './App.module.css';

export default function App() {
  const [status, setStatus] = useState('empty');
  const [letterHtml, setLetterHtml] = useState('');
  const [mode, setMode] = useState('');
  const [lastFormData, setLastFormData] = useState(null);

  const runGeneration = useCallback(async (formData) => {
    setLastFormData(formData);
    setStatus('generating');

    try {
      let rawText = '';
      let modeText = '';

      try {
        rawText  = await callGeminiAPI(formData);
        modeText = '✨ Generated by Google Gemini AI';
      } catch (apiErr) {
        const msg = apiErr.message || '';
        const isNoKey    = msg === 'NO_API_KEY';
        const isQuota    = msg.toLowerCase().includes('quota');
        const isNotFound = msg.toLowerCase().includes('not found') || msg.toLowerCase().includes('not supported');

        if (isNoKey || isQuota || isNotFound) {
          await new Promise((r) => setTimeout(r, 2000));
          rawText = buildTemplateLetter(formData);
          if (isQuota) {
            modeText = '⚠️ Gemini quota exceeded — Simulation mode active';
          } else if (isNotFound) {
            modeText = '⚠️ Gemini model unavailable — Simulation mode active';
          } else {
            modeText = '📄 Simulation Mode — Add VITE_GEMINI_API_KEY in .env to enable AI';
          }
        } else {
          throw apiErr;
        }
      }

      setLetterHtml(markdownToHtml(rawText));
      setMode(modeText);
      setStatus('result');
    } catch (err) {
      setLetterHtml(
        `<p style="color:var(--accent-red)">⚠️ Error: ${err.message}</p>
         <p>Check your <code>.env</code> file and make sure <strong>VITE_GEMINI_API_KEY</strong> is set correctly.</p>`
      );
      setMode('❌ Generation failed');
      setStatus('result');
    }
  }, []);

  const handleGenerate = useCallback((formData) => runGeneration(formData), [runGeneration]);

  const handleRegenerate = useCallback(() => {
    if (lastFormData) runGeneration(lastFormData);
  }, [lastFormData, runGeneration]);

  return (
    <>
      <Header />
      <Hero />
      <main className={styles.main}>
        <div className={styles.workspace}>
          <CoverForm onGenerate={handleGenerate} isLoading={status === 'generating'} />
          <OutputPanel
            status={status}
            letterHtml={letterHtml}
            mode={mode}
            onRegenerate={handleRegenerate}
          />
        </div>
      </main>
      <footer className={styles.footer}>
        CoverCraft AI &mdash; Sprint 4 &bull; Built with ❤️ using React + Gemini API
      </footer>
    </>
  );
}
